; Run all day simulations
(rule
 (alias runtest)
 (deps
  hardcaml/day01/simulate.exe
  common/test_vectors/day01.txt)
 (action
  (run ./hardcaml/day01/simulate.exe common/test_vectors/day01.txt)))

; Run verification
(rule
 (alias runtest)
 (deps
  hardcaml/day01/verify.exe
  common/test_vectors/day01.txt)
 (action
  (run ./hardcaml/day01/verify.exe common/test_vectors/day01.txt)))
